### ISSUE TITLE
NOT AN ISSUE but how does this work

### ISSUE THREAD

**Issue by marcroelse** [AntumDeluge/bin2header#2]
i am new to these kind of stuff but i can't get it to run yesterday i waisted 3 hours on this and today already 2 and i can't get my grasp on what it is i downloaded this git and also the sourceforge version.

:(
greeting 
marc

**Comment by AntumDeluge** [comment]
Are you getting any kind of message?

You might want to try & older version. There could be a problem with the current one.

**Comment by marcroelse** [comment]
when i used the version of sourceforge i got this
"[0910/102836.580:ERROR:crash_report_database_win.cc(428)] unexpected header"

i will now try an older version

**Comment by AntumDeluge** [comment]
I looked up that error. But everything that references it is related to Windows 10 or Google Chrome.

There is currently a problem where it cannot convert files over a certain size. But it's a different error message that appears.

Are you running it from the command line or by mouse click? It is a command line program so will only work as such:

```
bin2header <file>
```

If you have [Python](https://python.org/) on your computer, you can try the [Python version](https://github.com/AntumDeluge/bin2header/releases/download/v0.1.2/bin2header-0.1.2-py.tar.gz). It seems to have less problems.

**Comment by marcroelse** [comment]
i didn't know about the comandpromt i did that now i get 

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::erase: __pos (which is 4294967295) > this->size() (which is 13)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by AntumDeluge** [comment]
Yes, that's the current problem it is facing. That means that the file size is too large for it to handle. I need to work on a fix. I believe the [Python version](https://github.com/AntumDeluge/bin2header/releases/download/v0.1.2/bin2header-0.1.2-py.tar.gz) is able to handle large files. But you need the [Python interpreter](https://www.python.org/) installed on your system to use it.

**Comment by marcroelse** [comment]
if it is not an problem to ask i am doing the same thing with the python as the other version but i get an invalid syntax of my file name do i need to do something different?

**Comment by AntumDeluge** [comment]
Oh! You may be using an older Python interpreter. It needs at least Python version 3.

**Comment by marcroelse** [comment]
this is weird i installed the latest version of python but when i check the version in the cmd i get that i have version 2.7

**Comment by AntumDeluge** [comment]
Yes, Python has the version 2.x series & version 3.x series. You need latest 3.x version, which is currently 3.7.4: https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe

**Comment by marcroelse** [comment]
yes i downloaded that but when i do cmd at my file location and type python i get the 2.7 version

but i have downloaded the 3.7 version

can't i use that in the cmd or does that not mather

**Comment by AntumDeluge** [comment]
It is because your system has priority placed on the 2.7 version over the 3.7 version. You will either need to adjust your ***PATH*** environment variable, or uninstall version 2.7. After you uninstall 2.7, you may need to re-install version 3.7 to set up the environment correctly.

**Comment by AntumDeluge** [comment]
I figured out the bug in the non-Python version. It's not reading files that aren't nested in a directory structure. So...

This will fail:
```
bin2header foo.txt
```

But this will work:
```
bin2header .\\foo.txt
```

I am working on fixing this issue now.

**Comment by marcroelse** [comment]
what you said does do something different now whit my file the project just crash and doesn't give an error message in the console

**Comment by marcroelse** [comment]
now i got the right python installed but how do i use the python version ??

**Comment by AntumDeluge** [comment]
As long a  Python is installed correctly, you use it the same way as the non-Python version.

```
bin2header <filename>
```

Or you can do it like this:
```
python bin2header <filename>
```

If Python is not installed correctly, you have to use the full path to the Python executable. Example:
```
C:\Python37\python.exe bin2header <filename>
```

**Note:** Don't actually use the &lt; and &gt; symbols. Those are just to denote that you need to put the filename after the `bin2header` command. So, for example, if the file you want to convert is named "foo.txt", then you would do this:

```
bin2header foo.txt
```

or

```
bin2header path\to\foo.txt
```

**Comment by marcroelse** [comment]
when i does that it opends the tar.gz file but it asked for what program to use it with i used code but that doesn't realy help me.

when i use it with python in front of it i get this
 File "bin2header-0.1.2-py (3).tar.gz", line 1
SyntaxError: Non-UTF-8 code starting with '\x8b' in file bin2header-0.1.2-py (3).tar.gz on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

i really appreciate your help

**Comment by AntumDeluge** [comment]
A **.tar.gz** file is an archive, like a **.zip** file. You need to extract the contents just like you would a .zip archive. If you don't have anything that can extract a .tar.gz archive, you can install [7-zip](https://www.7-zip.org/).

**Comment by marcroelse** [comment]
when i just killed myself becouse that was stupid of me i use bin2header <filename> it doesn't recognise it the file that was in the tar that has that name doesn't have an extension don't know if that is normal or not

**Comment by AntumDeluge** [comment]
You may need to add ".py" extension to the file, so it is "bin2header.py".

**Comment by marcroelse** [comment]
this file was in the tar that was linked in this conversation i find it an bit of an weird file inhoud



[bin2header - Copy.zip](https://github.com/AntumDeluge/bin2header/files/3596175/bin2header.-.Copy.zip)

**Comment by marcroelse** [comment]
i just got the raw code from the git and put that in the file

**Comment by marcroelse** [comment]
oke i got the code running now but i get so many errors i don't know what is happening maby it is becouse i copied and paste the file in here so it is not compressed but don't think that matters

**Comment by marcroelse** [comment]
i believe it works now i have an header file and it looks good so gone test it on my program i needed it for.

**Comment by AntumDeluge** [comment]
Just released a fixed [version 0.1.3](https://github.com/AntumDeluge/bin2header/releases/tag/v0.1.3). You can test it out to see if it works.

**Comment by marcroelse** [comment]
I wil test it after i am done with my other test of the application

**Comment by marcroelse** [comment]
so i tested your new version and it still crashed if you want to know my bin file is 7000 kb

your python version works great

**Comment by AntumDeluge** [comment]
Fixed with commit 805580e. Will have new release out soon.

**Comment by marcroelse** [comment]
version 2.0 works perfect and saves me around half an hour of waiting each day thanks

**Comment by AntumDeluge** [comment]
Thank you for the feedback.

You might be able to tinker with the `-s` option & make it go even faster. Not sure though. By default it is set to 1048576 (1 megabyte). I'm not sure what the optimal chunk size would be. I suppose it would depend on the machine it's running on.

**Comment by marcroelse** [comment]
to give you an idee i change 7000 kb of bin file to an header file in 5seconds
