### ISSUE TITLE
bin2header generates invalid identifier names

### ISSUE THREAD

**Issue by howardjones** [AntumDeluge/bin2header#3]
I have a series of files called things like `36.bin` - bin2header will generate an array called 36 with #defines for 36_H. Neither of those are valid names.

It should really know what a valid C identifier looks like to warn you. Or perhaps allow the user to supply a name on the command line? Or add a prefix (e.g. DATA) to the front of names starting with a digit?

**Comment by AntumDeluge** [comment]
Thank you for pointing this out.

**Comment by AntumDeluge** [comment]
I believe @knl-le's solution has fixed this. But I'm going to leave it open because I want to add the option to supply your own name from the command line.

**Comment by AntumDeluge** [comment]
Fixed in #6 & #7
